site_name: Keep it simple !
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: indigo
  font:
    text: Roboto Mono
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/infinity
  features:
    - navigation.tracking
    # - navigation.indexes
    - search.suggest
    - search.share
nav:
  # - font: Roboto Mono
  - Golang:
      - golang/index.md
    # - Page 1: section/page-1.md
    # - Page n: section/page-n.md
  - Apache-Kafka:
      - kafka/index.md
  - Kubernetes:
      - kubernetes/index.md
  - Apache-Spark:
      - spark/index.md
  - Python:
      - python/index.md
  - Data Structures and Algorithms:
      - dsa/index.md
plugins:
  - search:
      separator: '[\s\-\.]'
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    # cookies:
    #   analytics: Google
    actions:
      - accept
      - manage
      - reject
  plugins:
    - privacy:
        external_assets: bundle
        external_assets_dir: assets/external
copyright: >
  Copyright &copy; 2022 - Raxit Solanki.
